# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='date',
            field=models.DateField(default=datetime.date(2016, 5, 14)),
            preserve_default=False,
        ),
    ]
