# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_moment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='suggested_category',
            field=models.ForeignKey(blank=True, max_length=1024, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_category', to='moments.Category'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='category',
            field=models.ForeignKey(blank=True, max_length=1024, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to='moments.Category'),
        ),
    ]
