# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0003_auto_20160514_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
