# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0004_auto_20160515_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='suggested_category',
        ),
    ]
